## run node test build pipeline
---
resource_types:
- name: npm
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/Anshita15/nodeRepo.git
    branch: master

# - name: package
#   type: npm
#   source:
#     endpoint: http://localhost:8081/artifactory
#     repository: /npm-local/
#     username: ((repo-username))
#     password: ((repo-password))

# - name: nodejs.org-git
#   type: git
#   icon: github-circle
#   source:
#     uri: https://github.com/nodejs/nodejs.org.git

jobs:
- name: publishing-app
  plan: 
  - get: source-code
#   - get: package
  - task: publish-app
    config:
        platform: linux
        image_resource:
            type: registry-image
            source: {repository: node, tag: "8" }
        inputs:
        - name: source-code
        outputs:
        - name: test-results
        run: 
         path: /bin/sh
         args:
         - -c
         - |
            echo "Node Version: $(node --version)"
            echo "NPM Version: $(npm --version)"
            export CHROME_BIN='/usr/bin/chromium'
            cd source-code
            cd firstApp
            npm install
            npm config set registry https://www.npmjs.com/
            npm config set username anshita15
            npm config set password Anshita@15
            npm config set email anshitasingh101@gmail.com
            npm config set strict-ssl false
            npm whoami
            npm config get password
            npm publish
    
            

    